### ISSUE TITLE
Issue rendering SVG from draw.io

### ISSUE THREAD

**Issue by alexfederlin** [mogest/prawn-svg#107]
Hi. I'm exporting an SVG from draw.io to use it in my PDF generated with asciidoctor-pdf. The rendering of text inside boxes does not really work. I have attached the following files inside the zip file:

- draw.io xml file
- exported svg files (with and w/o included copy of diagram)
- used adoc document
- resulting pdf file

Asciidoctor used: Asciidoctor PDF 1.5.0.alpha.16 using Asciidoctor 1.5.8
praw-svg gem (via gem list --local): 0.27.1

The SVGs display fine using a Chrome.

[asciidoc-troubleshooting.zip](https://github.com/mogest/prawn-svg/files/2951765/asciidoc-troubleshooting.zip)

**Comment by mogest** [comment]
Hi @alexfederlin.  Sorry to say, your SVG documents have HTML embedded as a "foreign object" inside them, and prawn-svg does not and will never support HTML.

I don't really know much about the stack you're using, but make sure you're not introducing any html yourself, and otherwise have a chat with the Asciidoctor PDF team regarding whether it's possible to keep html out of the svg document.  Good luck!

**Comment by alexfederlin** [comment]
Thanks. The SVGs are created with http://draw.io
With your input, I did some more research which showed that they are aware of the issue: https://desk.draw.io/support/solutions/articles/16000042487-why-does-the-text-of-svg-export-sometimes-not-display-correctly-in-ie-and-some-svg-editors-

Again, thanks for your help!
