### ISSUE TITLE
gradientTransform on linearGradient is not supported

### ISSUE THREAD

**Issue by thomasheinen** [mogest/prawn-svg#112]
Hi,

I have encountered an SVG which is not correctly rendered. Only the outer black ring is shown. The inner blue flames are not rendered at all. Batik and other programs render it correctly.

I have two versions of the same SVG (converted with inkscape from EPS using different converters). Both are not working.

I don't think this issue is related to #85 or #87 but I might be mistaken.
Could you please look into it? Thanks in advance.

Thomas.

[broken-svgs.zip](https://github.com/mogest/prawn-svg/files/3533479/broken-svgs.zip)

**Comment by mogest** [comment]
Hi @thomasheinen, thanks for posting.

That's an absolutely enormous SVG file you've supplied—could you please narrow the scope for me by paring it down to a minimal file that still reproduces the error?  Happy to dig into it at that point.

**Comment by thomasheinen** [comment]
Hi @mogest 

Thanks for your fast reply. You are right, sorry. It was not very thoughtful of me to whip such a big file into your face. :smile: 

Please find attached a minimal example. The black circle is rendered correctly. The blue "egg" vanishes in the PDF, but is rendered in external programs and the HTML version correctly.

[broken-svg-minimal.zip](https://github.com/mogest/prawn-svg/files/3533719/broken-svg-minimal.zip)

**Comment by mogest** [comment]
Ah, OK the first clue is that it does spit out a warning:

> prawn-svg does not yet support gradients with a non-identity gradientTransform attribute

I don't actually know what that even means (yes I wrote that error message!) so I'll go looking.

**Comment by mogest** [comment]
Ah, OK.  Because the `<linearGradient>` elements in your document have `gradientTransform` attributes, it's skipping the gradient altogether which makes it not render.

I took those attributes out and it doesn't render correctly (it looks like it's missing the fade-out altogether.)

I tried a bit of hackery, the gradients are handled by Prawn but I managed to monkey patch the method that applies the transformation matrix to the gradient and multiply the supplied gradient on the attribute.  Unfortunately I must be misunderstanding something, because it's all one colour after I do that.

This is probably not a super easy fix I'm sorry to say.  I'll keep it open in case I want to beat my head against a wall sometime :)

**Comment by thomasheinen** [comment]
Hm okay. Maybe we'll have a look at it ourselves, but we are no Ruby programmers here. :sweat_smile: We are just using ASCII Doc for some fancy reporting in our framework and stumbled upon the problem with that SVG.

Thanks for looking into it anyway, and some hard head-banging on your side would be much appreciated. :wink: :metal:

**Comment by mogest** [comment]
Would you believe... I actually managed to get it going.  Still needs a lot of tidying up since I have to monkey patch Prawn (their release cycle is slow) but if you want to try it out on the `issue-112` branch please do!

[logo-gas.svg.pdf](https://github.com/mogest/prawn-svg/files/3536079/logo-gas.svg.pdf)

**Comment by mogest** [comment]
All done, it'll go out with the next release.

**Comment by thomasheinen** [comment]
I can confirm that the patch is working. Thanks very much for your effort. :+1:
