### ISSUE TITLE
stroke="transparent" is not interpreted correctly

### ISSUE THREAD

**Issue by siddjain** [mogest/prawn-svg#128]
the issue was originally reported here:
https://discuss.asciidoctor.org/How-to-get-rid-of-border-around-SVG-images-td8284.html

is this the correct place to report this issue? thanks.

**Comment by mojavelinux** [comment]
It's not correct to say that prawn-svg is adding a unnecessary border. The correct way to explain this is that prawn-svg seems to be interpreting the color "transparent" as black. In the image in question, the stroke is being applied to a polygon which itself is creating a border around the canvas.

```xml
<polygon fill="white" stroke="transparent" points="-4,4 -4,-403 220,-403 220,4 -4,4"/>
```

**Comment by mogest** [comment]
Hi there @siddjain, and thank you @mojavelinux again for your fast analysis!

`transparent` isn't part of [the SVG 1.1 spec](https://www.w3.org/TR/SVG11/painting.html#SpecifyingPaint), and prawn-svg is an SVG 1.1 parser.  From your link it looks like it says it's a SVG 1.1 document too, so sorry to send you on a goose chase but your issue is with graphviz.  They should be using `none`.

**Comment by mojavelinux** [comment]
@mogest I had a strong feeling that was the case. Thanks for clarifying!

**Comment by Alwinator** [comment]
@mojavelinux I have the same problem as the initial author. I reported the issue to Graphviz: https://gitlab.com/graphviz/graphviz/-/issues/2192

**Comment by mojavelinux** [comment]
Looks like this issue has been previously reported as https://gitlab.com/graphviz/graphviz/-/issues/1863
